### ISSUE TITLE
Las clases deben estar organizadas en paquetes (22 décimas)

### ISSUE THREAD

**Issue by gfhuertac** [rodrigomartinezar/prueba0_lyp#1]
- Tanto las pintas como las clases asociadas (Carta, Baraja, ...) deben estar en un paquete 

común.
- Las pintas deberían estar en un subpaquete propio (dentro del paquete de las clases 

principales)
Por ejemplo:
Clase Carta en cl.uai.naipe
Clase Corazon en cl.uai.naipe.pintas

**Comment by rodrigomartinezar** [comment]
Issue Corregido en commit https://github.com/rodrigomartinezar/prueba0_lyp/commit/e0c4855e0f57b354cdf39bcaef74f2f828d234f8
