### ISSUE TITLE
Los constructores de la subclase deben llamar al constructor de la clase Carta con los   parámetros necesarios (9 décimas)

### ISSUE THREAD

**Issue by gfhuertac** [rodrigomartinezar/prueba0_lyp#3]
La clase carta ya define un constructor con la asignación de datos. Deben ocupar ese  constructor desde la clase hija, no asignar directamente los datos.

**Comment by rodrigomartinezar** [comment]
Issue corregido en commit https://github.com/rodrigomartinezar/prueba0_lyp/commit/df652ddc9b78c46f722dd8154cc01c58b7c06279
